from fpdf import FPDF
from models import IRRACOutput


# FPDF's core Helvetica font is Latin-1 only. The model regularly emits
# em-dashes, smart quotes, ellipses, and other Unicode that crashes
# FPDFUnicodeEncodingException. Translate the common offenders to ASCII
# equivalents before any text reaches the PDF.
_UNICODE_REPLACEMENTS = {
    "—": "--",   # em dash
    "–": "-",    # en dash
    "−": "-",    # minus sign
    "‘": "'",    # left single quote
    "’": "'",    # right single quote / apostrophe
    "“": '"',    # left double quote
    "”": '"',    # right double quote
    "…": "...",  # horizontal ellipsis
    "•": "*",    # bullet
    "‐": "-",    # hyphen
    "‑": "-",    # non-breaking hyphen
    " ": " ",    # non-breaking space
    "​": "",     # zero-width space
}


def _safe(text: str) -> str:
    """Make text safe for the core Latin-1 PDF font."""
    if not text:
        return ""
    for src, dst in _UNICODE_REPLACEMENTS.items():
        text = text.replace(src, dst)
    # Final guard: drop anything still outside Latin-1 rather than crashing.
    return text.encode("latin-1", errors="replace").decode("latin-1")


class IRACPDF(FPDF):
    def __init__(self, area: str):
        super().__init__()
        self.area = area
        self.set_auto_page_break(auto=True, margin=22)
        self.set_margins(18, 18, 18)

    def header(self):
        # Dark header bar
        self.set_fill_color(20, 20, 19)
        self.rect(0, 0, 210, 32, "F")
        # Orange accent line
        self.set_fill_color(217, 119, 87)
        self.rect(0, 32, 210, 2, "F")
        # Title
        self.set_font("Helvetica", "B", 17)
        self.set_text_color(250, 249, 245)
        self.set_xy(18, 9)
        self.cell(120, 8, "IRAC Maker", align="L")
        # Area label
        self.set_font("Helvetica", "", 10)
        self.set_text_color(176, 174, 165)
        self.set_xy(18, 20)
        self.cell(0, 6, f"Area of Law: {self.area}", align="L")
        self.set_xy(0, 40)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(176, 174, 165)
        self.cell(
            0, 8,
            "For educational purposes only. Not legal advice. Generated by IRAC Maker.",
            align="C",
        )
        self.set_text_color(217, 119, 87)
        self.set_x(-30)

    def section_header(self, label: str, accent_rgb=(217, 119, 87)):
        # Accent left bar
        self.set_fill_color(*accent_rgb)
        x, y = self.get_x(), self.get_y()
        self.rect(x, y, 3, 7, "F")
        self.set_x(x + 6)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(30, 29, 27)
        self.cell(0, 7, _safe(label), new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def section_body(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(55, 52, 46)
        self.multi_cell(0, 6, _safe(text))
        self.ln(7)

    def add_facts(self, facts: str):
        self.set_fill_color(245, 243, 237)
        y = self.get_y()
        self.rect(18, y, 174, 6, "F")
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(100, 95, 85)
        self.set_xy(18, y)
        self.cell(0, 6, "FACTS", align="L")
        self.ln(8)
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(80, 76, 68)
        self.multi_cell(0, 6, _safe(facts))
        self.ln(8)
        # Divider
        self.set_draw_color(220, 216, 205)
        self.line(18, self.get_y(), 192, self.get_y())
        self.ln(8)


SECTION_COLORS = {
    "issue":       (217, 119, 87),
    "rule_stmt":   (106, 155, 204),
    "rule_expl":   (106, 155, 204),
    "application": (217, 119, 87),
    "conclusion":  (120, 140, 93),
    "tips":        (176, 174, 165),
}


def export_to_pdf(result: IRRACOutput, facts: str, area: str) -> bytes:
    pdf = IRACPDF(area)
    pdf.add_page()

    if facts.strip():
        pdf.add_facts(facts.strip())

    sections = [
        ("I — Issue", result.issue, SECTION_COLORS["issue"]),
        ("R1 — Rule Statement", result.rule_statement, SECTION_COLORS["rule_stmt"]),
        ("R2 — Rule Exploration", result.rule_exploration, SECTION_COLORS["rule_expl"]),
        ("A — Application", result.application, SECTION_COLORS["application"]),
        ("C — Conclusion", result.conclusion, SECTION_COLORS["conclusion"]),
    ]
    for label, content, color in sections:
        pdf.section_header(label, color)
        pdf.section_body(content)

    if result.tips:
        pdf.section_header("Common Mistakes to Avoid", SECTION_COLORS["tips"])
        for i, tip in enumerate(result.tips, 1):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(80, 76, 68)
            pdf.multi_cell(0, 6, _safe(f"{i}. {tip}"))
            pdf.ln(2)

    return bytes(pdf.output())
